name             'acme_test'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache-2.0'
description      'Installs/Configures acme_test'
version          '0.1.0'

depends          'bind'
depends          'osl-acme'
depends          'osl-apache'
depends          'osl-postgresql'
depends          'selinux'
