---
verifier:
  name: inspec
suites:
  - name: default
    run_list:
      - recipe[osl-acme::default]
  - name: server
    run_list:
      - recipe[osl-acme::server]
      - recipe[acme_test]
    attributes:
      osl-acme:
        pebble:
          host_aliases:
            - foo.org
