---
suites:
  - name: default
    run_list:
      - recipe[osl-acme::default]
  - name: server
    driver:
      flavor_ref: 'm1.medium'
    run_list:
      - recipe[osl-acme::server]
    excludes:
      - centos-6
