name             'osl-acme'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'apachev2'
issues_url       'https://github.com/osuosl-cookbooks/osl-acme/issues'
source_url       'https://github.com/osuosl-cookbooks/osl-acme'
description      'Installs/Configures osl-acme'
long_description 'Installs/Configures osl-acme'
version          '0.1.0'

depends          'acme', '~> 3.0.0'
depends          'compat_resource', '>= 12.19'
depends          'osl-letsencrypt-boulder-server'
depends          'poise-python'
depends          'rabbitmq', '~> 5.0'

supports         'centos', '~> 6.0'
supports         'centos', '~> 7.0'
